name: Create Issue When Build Fails

on:
  push:

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Simulate failure
        run: exit 1

      - name: Create Issue
        if: failure()
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title":"Build failed",
              "body":"The workflow failed."
            }'

      - name: Always run
        if: always()
        run: |
          echo "I should run"
